### ISSUE TITLE
Title jumps

### ISSUE THREAD

**Issue by Yalyenea** [Myriad-Dreamin/tinymist#916] opened 2024-11-29 14:47 UTC
Title jumps will automatically go to the table of contents in the preview PDF（too slow and bad）, and we hope they can jump to the location of the title in the main text.

**Comment by Eric-Song-Nop** [comment] 2024-11-30 01:32
Yes, jump to TOC constantly during writing does not really make much sense.

**Comment by Myriad-Dreamin** [comment] 2024-11-30 08:13
Duplicate of #626

**Closed** 2024-11-30 08:13 UTC
Labels: enhancement, document-preview
