### ISSUE TITLE
Fail to jump back to the code for package "gentle-clues" when clicking on preview

### ISSUE THREAD

**Issue by Asta-Q** [Myriad-Dreamin/tinymist#872] opened 2024-11-21 03:09 UTC
I am not sure whether it is a bug or the package cause it. I am using the tinymist VScode extension on Windows, and use the pacakge "gentle-clues" to generate a box. But when I click on the content in the box generated by the pacakge, it fails to jump the corresponding code.

**Comment by Myriad-Dreamin** [comment] 2024-11-21 03:19
duplicate of #581

**Closed** 2024-11-21 03:19 UTC

**Comment by Asta-Q** [comment] 2024-11-23 10:52
Sorry to bother, I find my problem is somewhat different from https://github.com/Myriad-Dreamin/tinymist/issues/581.
I am not familiar with codes, so I cannot figure out whether they are essentially same.
When use the code
```typ
#import "@preview/gentle-clues:1.0.0": *

#tip[content]

First paragraph

Second paragraph

Third paragraph
```
When I click on the content, it does not jump to anywhere, instead of jumping to the module source code as https://github.com/Myriad-Dreamin/tinymist/issues/581.
When I click on the first paragraph, it will not jump anywhere, either.
When I click on the second paragraph, it will jump to the first paragraph.
