### ISSUE TITLE
Semantic highlighting unusable with unicodes in Neovim

### ISSUE THREAD

**Issue by Zeta611** [Myriad-Dreamin/tinymist#735] opened 2024-10-27 06:08 UTC
**Describe the bug**
In Neovim (LazyVim dist), semantic highlighting does not work with documents with unicodes.
Here is an asciinema cast of editing a short Typst document with `℘` character:
[![asciicast](https://asciinema.org/a/hJdbC43OQyJWcsvlEu7GDUrF7.svg)](https://asciinema.org/a/hJdbC43OQyJWcsvlEu7GDUrF7)

Turning off semantic highlighting "resolves" the issue, but completely disables syntax highlighting.

**Package/Software version:**

Neovim version:
```plain
𝝺 nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

OS version:
```plain
macOS 15.0.1 (24A348)
```

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
𝝺 /Users/jay/.local/share/nvim/mason/bin/tinymist --version
tinymist
Build Timestamp:     2024-10-19T17:12:03.217404000Z
Build Git Describe:  v0.12.0
Commit SHA:          4437b3bffb5f01f06bd64e4e424480ba72a88619
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
Typst Version:       0.12.0
Typst Source:        git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymist-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9
```

**Logs:**

tinymist server log(`:LspLog`):
```plain
[START][2024-10-27 14:41:36] LSP logging initiated
[ERROR][2024-10-27 14:41:36] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	'[2024-10-27T05:41:36Z INFO  tinymist] tinymist LSP version information: [["Build Timestamp", "2024-10-19T17:12:03.217404000Z"], ["Build Git Describe", "v0.12.0"], ["Commit SHA", "4437b3bffb5f01f06bd64e4e424480ba72a88619"], ["Commit Date", "None"], ["Commit Branch", "None"], ["Cargo Target Triple", "aarch64-apple-darwin"], ["Typst Version", "0.12.0"], ["Typst Source", "git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymist-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9"]]\n[2024-10-27T05:41:36Z INFO  tinymist] starting LSP server: LspArgs {\n        mirror: MirrorArgs {\n            mirror: "",\n            replay: "",\n        },\n        font: CompileFontArgs {\n            font_paths: [],\n            ignore_system_fonts: false,\n        },\n    }\n[2024-10-27T05:41:36Z INFO  sync_lsp] handling initialize - (1) at Instant { tv_sec: 198289, tv_nsec: 835520583 }\n[2024-10-27T05:41:36Z INFO  tinymist::init] preferred theme: None {}\n[2024-10-27T05:41:36Z INFO  tinymist::server] LanguageState: initialized with config Config { const_config: ConstConfig { position_encoding: Utf16, cfg_change_registration: true, notify_will_rename_files: true, tokens_dynamic_registration: false, tokens_overlapping_token_support: true, tokens_multiline_token_support: false, doc_line_folding_only: true, doc_fmt_dynamic_registration: true }, compile: CompileConfig { roots: ["/Users/jay/Documents/error"], output_path: PathPattern(""), export_pdf: Never, root_path: None, font_opts: CompileFontArgs { font_paths: [], ignore_system_fonts: false }, system_fonts: None, font_paths: [], fonts: OnceCell(Uninit), notify_status: false, periscope_args: None, typst_extra_args: Some(CompileExtraOpts { root_dir: None, entry: None, inputs: {}, font: CompileFontArgs { font_paths: [], ignore_system_fonts: false }, creation_timestamp: None, cert: None }), preferred_theme: None, has_default_entry_path: false, lsp_inputs: {"x-preview": "{\\"version\\":1,\\"theme\\":\\"\\"}"} }, semantic_tokens: Enable, formatter_mode: Disable, formatter_print_width: None }\n[2024-10-27T05:41:36Z INFO  tinymist::actor] TypstActor: creating server for primary, entry: EntryState { rooted: true, root: Some("/Users/jay/Documents/error"), main: None }, inputs: {"x-preview": "{\\"version\\":1,\\"theme\\":\\"\\"}"}\n[2024-10-27T05:41:36Z INFO  tinymist::init] creating SharedFontResolver with CompileFontArgs { font_paths: [], ignore_system_fonts: false }\n[2024-10-27T05:41:36Z INFO  sync_lsp] handled  initialize - (1) in 430.71µs\n'
[ERROR][2024-10-27 14:41:36] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	'[2024-10-27T05:41:36Z INFO  sync_lsp] notifying initialized - at Instant { tv_sec: 198289, tv_nsec: 844317166 }\n[2024-10-27T05:41:36Z INFO  tinymist::server] server initialized\n[2024-10-27T05:41:36Z INFO  sync_lsp] notifing initialized succeeded in 21.79µs\n[2024-10-27T05:41:36Z INFO  sync_lsp] notifying workspace/didChangeConfiguration - at Instant { tv_sec: 198289, tv_nsec: 844377583 }\n[2024-10-27T05:41:36Z INFO  tinymist::init] preferred theme: None {"exportPdf": String("onType")}\n[2024-10-27T05:41:36Z INFO  tinymist::server] new settings applied\n[2024-10-27T05:41:36Z INFO  sync_lsp] notifing workspace/didChangeConfiguration succeeded in 36.83µs\n[2024-10-27T05:41:36Z INFO  sync_lsp] notifying textDocument/didOpen - at Instant { tv_sec: 198289, tv_nsec: 844440250 }\n[2024-10-27T05:41:36Z INFO  tinymist::server] did open Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/jay/Documents/error/error.typ", query: None, fragment: None }\n[2024-10-27T05:41:36Z INFO  tinymist::server] create source: "/Users/jay/Documents/error/error.typ"\n[2024-10-27T05:41:36Z INFO  tinymist::actor::typ_client] the entry file of TypstActor(primary) is changing to EntryState { rooted: true, root: Some("/Users/jay/Documents/error"), main: Some(/error.typ) }\n[2024-10-27T05:41:36Z INFO  tinymist::server] file focused[implicit,o]: Some("/Users/jay/Documents/error/error.typ")\n[2024-10-27T05:41:36Z INFO  sync_lsp] notifing textDocument/didOpen succeeded in 77.25µs\n[2024-10-27T05:41:36Z INFO  sync_lsp] handling textDocument/documentSymbol - (2) at Instant { tv_sec: 198289, tv_nsec: 844627625 }\n[2024-10-27T05:41:36Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 4.791µs\n[2024-10-27T05:41:36Z INFO  sync_lsp] handled  textDocument/documentSymbol - (2) in 47.58µs\n[2024-10-27T05:41:36Z INFO  sync_lsp] handling textDocument/inlayHint - (3) at Instant { tv_sec: 198289, tv_nsec: 845401125 }\n'
[ERROR][2024-10-27 14:41:36] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:36Z INFO  sync_lsp] handling textDocument/documentSymbol - (4) at Instant { tv_sec: 198289, tv_nsec: 867579458 }\n[2024-10-27T05:41:36Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 12.042µs\n[2024-10-27T05:41:36Z INFO  sync_lsp] handled  textDocument/documentSymbol - (4) in 57.46µs\n"
[ERROR][2024-10-27 14:41:36] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:36Z INFO  sync_lsp] handling textDocument/inlayHint - (5) at Instant { tv_sec: 198289, tv_nsec: 887044833 }\n"
[WARN][2024-10-27 14:41:36] ...lsp/handlers.lua:135	"The language server tinymist triggers a registerCapability handler for workspace/didChangeConfiguration despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2024-10-27 14:41:36] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:36Z INFO  sync_lsp] handling textDocument/semanticTokens/full - (6) at Instant { tv_sec: 198289, tv_nsec: 887672833 }\n[2024-10-27T05:41:36Z INFO  sync_lsp] handled  textDocument/semanticTokens/full - (6) in 68.00µs\n"
[ERROR][2024-10-27 14:41:37] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	'[2024-10-27T05:41:37Z INFO  tinymist::actor::editor] received status request(primary) Compiling\n[2024-10-27T05:41:37Z INFO  sync_lsp] handled  textDocument/inlayHint - (5) in 248.38ms\n[2024-10-27T05:41:37Z INFO  sync_lsp] handled  textDocument/inlayHint - (3) in 290.06ms\n[2024-10-27T05:41:37Z INFO  tinymist::actor::editor] received diagnostics from primary:4: diag(Some(0))\n[2024-10-27T05:41:37Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess\n[2024-10-27T05:41:37Z INFO  tinymist::init] Check path Some(/error.typ) and root Some("/Users/jay/Documents/error") with output directory PathPattern("")\n[2024-10-27T05:41:37Z INFO  tinymist::task::export] RenderActor(Pdf { creation_timestamp: None }): exporting EntryState { rooted: true, root: Some("/Users/jay/Documents/error"), main: Some(/error.typ) } to "/Users/jay/Documents/error/error.pdf"\n[2024-10-27T05:41:37Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 8.417µs\n[2024-10-27T05:41:37Z INFO  tinymist::actor::editor] received status request(primary) Compiling\n[2024-10-27T05:41:37Z INFO  tinymist::actor::editor] received diagnostics from primary:5: diag(Some(0))\n[2024-10-27T05:41:37Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess\n[2024-10-27T05:41:37Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 4.375µs\n[2024-10-27T05:41:37Z INFO  tinymist::task::export] RenderActor(Pdf { creation_timestamp: None }): export complete\n'
[ERROR][2024-10-27 14:41:37] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:37Z INFO  sync_lsp] handling textDocument/documentSymbol - (7) at Instant { tv_sec: 198290, tv_nsec: 394224416 }\n[2024-10-27T05:41:37Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 4.083µs\n[2024-10-27T05:41:37Z INFO  sync_lsp] handled  textDocument/documentSymbol - (7) in 35.79µs\n"
[ERROR][2024-10-27 14:41:37] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:37Z INFO  sync_lsp] handling textDocument/documentHighlight - (8) at Instant { tv_sec: 198290, tv_nsec: 394797583 }\n"
[ERROR][2024-10-27 14:41:37] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:37Z INFO  sync_lsp] handled  textDocument/documentHighlight - (8) in 105.13µs\n"
[ERROR][2024-10-27 14:41:37] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:37Z INFO  sync_lsp] handling textDocument/documentSymbol - (9) at Instant { tv_sec: 198290, tv_nsec: 405093416 }\n"
[ERROR][2024-10-27 14:41:37] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:37Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 3.583µs\n[2024-10-27T05:41:37Z INFO  sync_lsp] handled  textDocument/documentSymbol - (9) in 25.50µs\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] notifying textDocument/didChange - at Instant { tv_sec: 198292, tv_nsec: 89399708 }\n[2024-10-27T05:41:39Z INFO  sync_lsp] notifing textDocument/didChange succeeded in 73.92µs\n[2024-10-27T05:41:39Z INFO  tinymist::actor::editor] received status request(primary) Compiling\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] handling textDocument/documentSymbol - (10) at Instant { tv_sec: 198292, tv_nsec: 89563875 }\n[2024-10-27T05:41:39Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 6.917µs\n[2024-10-27T05:41:39Z INFO  sync_lsp] handled  textDocument/documentSymbol - (10) in 50.42µs\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	'[2024-10-27T05:41:39Z INFO  tinymist::actor::editor] received diagnostics from primary:6: diag(Some(0))\n[2024-10-27T05:41:39Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess\n[2024-10-27T05:41:39Z INFO  tinymist::task::export] RenderActor(Pdf { creation_timestamp: None }): exporting EntryState { rooted: true, root: Some("/Users/jay/Documents/error"), main: Some(/error.typ) } to "/Users/jay/Documents/error/error.pdf"\n'
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 6.709µs\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] handling textDocument/inlayHint - (11) at Instant { tv_sec: 198292, tv_nsec: 90078333 }\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] handled  textDocument/inlayHint - (11) in 34.25µs\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  tinymist::task::export] RenderActor(Pdf { creation_timestamp: None }): export complete\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] notifying $/cancelRequest - at Instant { tv_sec: 198292, tv_nsec: 282544916 }\n[2024-10-27T05:41:39Z WARN  sync_lsp] unhandled notification: $/cancelRequest\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] handling textDocument/semanticTokens/full - (12) at Instant { tv_sec: 198292, tv_nsec: 282573375 }\n[2024-10-27T05:41:39Z INFO  sync_lsp] handled  textDocument/semanticTokens/full - (12) in 28.88µs\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] handling textDocument/documentSymbol - (13) at Instant { tv_sec: 198292, tv_nsec: 497242208 }\n[2024-10-27T05:41:39Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 4.458µs\n[2024-10-27T05:41:39Z INFO  sync_lsp] handled  textDocument/documentSymbol - (13) in 38.67µs\n[2024-10-27T05:41:39Z INFO  sync_lsp] handling textDocument/documentHighlight - (14) at Instant { tv_sec: 198292, tv_nsec: 497408291 }\n"
[ERROR][2024-10-27 14:41:39] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:39Z INFO  sync_lsp] handled  textDocument/documentHighlight - (14) in 43.33µs\n"
[ERROR][2024-10-27 14:41:40] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:40Z INFO  tinymist::actor::editor] received status request(primary) Compiling\n[2024-10-27T05:41:40Z INFO  tinymist::actor::editor] received diagnostics from primary:7: diag(Some(0))\n[2024-10-27T05:41:40Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess\n[2024-10-27T05:41:40Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 9.167µs\n[2024-10-27T05:41:40Z INFO  sync_lsp] notifying textDocument/didSave - at Instant { tv_sec: 198293, tv_nsec: 132611583 }\n"
[ERROR][2024-10-27 14:41:40] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:40Z INFO  sync_lsp] notifing textDocument/didSave succeeded in 27.71µs\n"
[ERROR][2024-10-27 14:41:40] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:40Z INFO  sync_lsp] handling textDocument/documentSymbol - (15) at Instant { tv_sec: 198293, tv_nsec: 352063416 }\n[2024-10-27T05:41:40Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 4.25µs\n[2024-10-27T05:41:40Z INFO  sync_lsp] handled  textDocument/documentSymbol - (15) in 41.50µs\n"
[ERROR][2024-10-27 14:41:40] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:40Z INFO  sync_lsp] handling textDocument/documentHighlight - (16) at Instant { tv_sec: 198293, tv_nsec: 352327125 }\n[2024-10-27T05:41:40Z INFO  sync_lsp] handled  textDocument/documentHighlight - (16) in 47.79µs\n"
[ERROR][2024-10-27 14:41:49] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:49Z INFO  sync_lsp] handling textDocument/documentHighlight - (17) at Instant { tv_sec: 198302, tv_nsec: 848626083 }\n"
[ERROR][2024-10-27 14:41:49] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:41:49Z INFO  sync_lsp] handled  textDocument/documentHighlight - (17) in 115.04µs\n"
[ERROR][2024-10-27 14:42:02] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:42:02Z INFO  sync_lsp] handling textDocument/documentHighlight - (18) at Instant { tv_sec: 198315, tv_nsec: 126042166 }\n"
[ERROR][2024-10-27 14:42:02] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jay/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-10-27T05:42:02Z INFO  sync_lsp] handled  textDocument/documentHighlight - (18) in 244.21µs\n"
```

tinymist client log(`:messages`):
```plain
Error executing vim.schedule lua callback: ...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: ...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149: index out of range
stack traceback:
	[builtin#36]: at 0x01049dd078
	...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'
	...eovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'wait'
	.../jay/.local/share/nvim/lazy/lazy.nvim/lua/lazy/async.lua:113: in function 'wait'
	...al/share/nvim/lazy/lazy.nvim/lua/lazy/manage/process.lua:235: in function <...al/share/nvim/lazy/lazy.nvim/lua/lazy/manage/process.lua:232>
	[C]: in function 'pcall'
	....local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/git.lua:192: in function 'get_tag_refs'
	....local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/git.lua:161: in function 'ref'
	....local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/git.lua:149: in function <....local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/git.lua:118>
	[C]: in function 'pcall'
	...al/share/nvim/lazy/lazy.nvim/lua/lazy/manage/checker.lua:43: in function 'fast_check'
	...al/share/nvim/lazy/lazy.nvim/lua/lazy/manage/checker.lua:15: in function 'start'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/config.lua:342: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: ...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149: index out of range
stack traceback:
	[builtin#36]: at 0x01049dd078
	...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'
	...eovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
"error.typ" 1L, 13B
```

**Additional context**
My LazyVim config file for tinymist:
```lua
return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "tinymist",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      "mason.nvim",
      "williamboman/mason-lspconfig.nvim",
    },
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        tinymist = {
          single_file_support = true,
          root_dir = function()
            return vim.fn.getcwd()
          end,
          -- capabilities = (function()
          --   -- Disable semantic tokens to avoid Unicode-related crashes
          --   local capabilities = vim.lsp.protocol.make_client_capabilities()
          --   capabilities.textDocument.semanticTokens = nil
          --   return capabilities
          -- end)(),
          on_attach = function(client, bufnr)
            -- Disable semantic highlighting
            -- client.server_capabilities.semanticTokensProvider = nil
          end,
          --- See [Tinymist Server Configuration](https://github.com/Myriad-Dreamin/tinymist/blob/main/Configuration.md) for references.
          settings = {
            exportPdf = "onType",
          },
        },
      },
    },
  },
}
```

Adding the following completely disables syntax highlighting, but the errors go away.
```lua
          on_attach = function(client, bufnr)
            -- Disable semantic highlighting
            client.server_capabilities.semanticTokensProvider = nil
          end,
```

FYI, I can use [kaarmu/typst](https://github.com/kaarmu/typst.vim) for syntax highlighting until the issue gets resolved.

**Comment by Myriad-Dreamin** [comment] 2024-10-27 08:01
duplicate of #638

**Closed by Myriad-Dreamin** 2024-10-27 08:01 UTC

**Comment by Zeta611** [comment] 2024-10-27 08:32
Sorry, the issue wasn't very discoverable--would you recommend using [this workaround](https://github.com/Myriad-Dreamin/tinymist/issues/638#issuecomment-2395941103) for now?

**Comment by Myriad-Dreamin** [comment] 2024-10-29 02:46
> would you recommend using https://github.com/Myriad-Dreamin/tinymist/issues/638#issuecomment-2395941103 for now?

@Zeta611 I don't encourage this, as we most editors and users rarely use `utf-8` position encoding, implying less robust and usability. But if you have any issue when using `utf-8` position encoding, please feel free to open an issue on GitHub.
