### ISSUE TITLE
tinymist Disconnection on nvim-lsp

### ISSUE THREAD

**Issue by lcdse7en** [Myriad-Dreamin/tinymist#713] opened 2024-10-20 09:28 UTC
![01](https://github.com/user-attachments/assets/5eebbb4f-6422-4f38-b914-b4883413b1f3)
**Describe the bug**

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.12-x64v4-xanmod1
```

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
tinymist 
Build Timestamp:     2024-03-22T02:18:18.207134800Z
Build Git Describe:  v0.11.1-rc2-5-gf0a96cb-dirty
Commit SHA:          f0a9...
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-pc-windows-msvc
Typst Version:       0.11.0
```

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain

```

tinymist client log(Help -> Toggle Developer Tools -> Console):
```plain

```

**Additional context**

**Comment by Eric-Song-Nop** [comment] 2024-10-20 10:31
Can you provide the Log for Tinymist, you can find it with the command `LspLog` or at `~/.local/state/nvim/lsp.log` since you seems to be using Neovim.

**Comment by lcdse7en** [comment] 2024-10-20 10:39
![02](https://github.com/user-attachments/assets/5e3205b1-ff47-4e36-b1de-571b0acc961f)
![03](https://github.com/user-attachments/assets/50fd835b-a5f3-4aa5-a210-76105e12482d)

**Comment by Myriad-Dreamin** [comment] 2024-10-24 16:21
The second screenshot hints that there is some misconfiguration happening, e.g. wrong position encoding handshaking.

**Comment by lcdse7en** [comment] 2024-10-26 10:06
The configuration bias is UTF-8
![IMG_20241026_180433](https://github.com/user-attachments/assets/e46859ae-56e4-4869-8128-c855138d0f30)

**Comment by Myriad-Dreamin** [comment] 2024-11-30 15:18
Possibly duplicate of #766. But whatever, for specific bug, it might be #766; to run tinymist in neovim, most users should be able to solve it by search solutions by google.

**Closed by Myriad-Dreamin** 2024-11-30 15:18 UTC
Labels: need-to-investigate
