### ISSUE TITLE
Broken word counter

### ISSUE THREAD

**Issue by Ivanmatthew** [Myriad-Dreamin/tinymist#793] opened 2024-11-11 15:49 UTC
**Describe the bug**
The word counter does not count correctly, as it ignores any first words of a line if it has an empty line before it’s own line.

To reproduce, create a typst file with the contents:
```plain
foo

bar

foobar

foo bar
```
The first and last word gets counted and nothing else inbetween 

**Package/Software version:**

tinymist extension version: `v0.12.0`.

**Comment by Eric-Song-Nop** [comment] 2024-11-11 21:10
Thanks for your report, I made a fix for this, which should work for this case, but might need more tests for all other cases.

**Comment by Myriad-Dreamin** [comment] 2024-11-12 06:09
The text exporter is known to be not quite correct. To fix this issue correctly, we should request typst to preserve space characters for text export, like [Add extra content hint](https://github.com/Myriad-Dreamin/typst/commit/2047886f15794317664f06c7eab769a278a52206), but I have no a convinced PR to do this gracefully. We may reimplement a robust text exporter based on HTML export in future.

**Comment by Myriad-Dreamin** [comment] 2024-11-15 06:57
Further tests could be performed to avoid regression but we can close it right now because it is fixed by https://github.com/Myriad-Dreamin/tinymist/pull/795.

**Closed by Myriad-Dreamin** 2024-11-15 06:57 UTC
